export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_SUCCEED = "PURCHASE_SUCCEED";
export const PURCHASE_FAIL = "PURCHASE_FAIL";
export const PURCHASE_LOADING = "PURCHASE_LOADING";
export const RESET_PURCHASE_UI = "RESET_PURCHASE_UI";